# Options for lists presented on the drug risk check page (medication_check_page)

SEX_OPTIONS = [
    {"label": "Male", "value": 1},
    {"label": "Female", "value": 2},
]

COUNTRY_OPTIONS = [
    {"label": "Any", "value": ""},
    {"label": "Afghanistan (AF)", "value": "AF"},
    {"label": "Albania (AL)", "value": "AL"},
    {"label": "Algeria (DZ)", "value": "DZ"},
    {"label": "Andorra (AD)", "value": "AD"},
    {"label": "Angola (AO)", "value": "AO"},
    {"label": "Antigua and Barbuda (AG)", "value": "AG"},
    {"label": "Argentina (AR)", "value": "AR"},
    {"label": "Armenia (AM)", "value": "AM"},
    {"label": "Australia (AU)", "value": "AU"},
    {"label": "Austria (AT)", "value": "AT"},
    {"label": "Azerbaijan (AZ)", "value": "AZ"},
    {"label": "Bahamas (BS)", "value": "BS"},
    {"label": "Bahrain (BH)", "value": "BH"},
    {"label": "Bangladesh (BD)", "value": "BD"},
    {"label": "Barbados (BB)", "value": "BB"},
    {"label": "Belarus (BY)", "value": "BY"},
    {"label": "Belgium (BE)", "value": "BE"},
    {"label": "Belize (BZ)", "value": "BZ"},
    {"label": "Benin (BJ)", "value": "BJ"},
    {"label": "Bhutan (BT)", "value": "BT"},
    {"label": "Bolivia (BO)", "value": "BO"},
    {"label": "Bosnia and Herzegovina (BA)", "value": "BA"},
    {"label": "Botswana (BW)", "value": "BW"},
    {"label": "Brazil (BR)", "value": "BR"},
    {"label": "Brunei (BN)", "value": "BN"},
    {"label": "Bulgaria (BG)", "value": "BG"},
    {"label": "Burkina Faso (BF)", "value": "BF"},
    {"label": "Burundi (BI)", "value": "BI"},
    {"label": "Cambodia (KH)", "value": "KH"},
    {"label": "Cameroon (CM)", "value": "CM"},
    {"label": "Canada (CA)", "value": "CA"},
    {"label": "Cape Verde (CV)", "value": "CV"},
    {"label": "Central African Republic (CF)", "value": "CF"},
    {"label": "Chad (TD)", "value": "TD"},
    {"label": "Chile (CL)", "value": "CL"},
    {"label": "China (CN)", "value": "CN"},
    {"label": "Colombia (CO)", "value": "CO"},
    {"label": "Comoros (KM)", "value": "KM"},
    {"label": "Congo (CG)", "value": "CG"},
    {"label": "Congo, Democratic Republic of (CD)", "value": "CD"},
    {"label": "Costa Rica (CR)", "value": "CR"},
    {"label": "Croatia (HR)", "value": "HR"},
    {"label": "Cuba (CU)", "value": "CU"},
    {"label": "Cyprus (CY)", "value": "CY"},
    {"label": "Czech Republic (CZ)", "value": "CZ"},
    {"label": "Denmark (DK)", "value": "DK"},
    {"label": "Djibouti (DJ)", "value": "DJ"},
    {"label": "Dominica (DM)", "value": "DM"},
    {"label": "Dominican Republic (DO)", "value": "DO"},
    {"label": "Ecuador (EC)", "value": "EC"},
    {"label": "Egypt (EG)", "value": "EG"},
    {"label": "El Salvador (SV)", "value": "SV"},
    {"label": "Estonia (EE)", "value": "EE"},
    {"label": "Eswatini (SZ)", "value": "SZ"},
    {"label": "Ethiopia (ET)", "value": "ET"},
    {"label": "Fiji (FJ)", "value": "FJ"},
    {"label": "Finland (FI)", "value": "FI"},
    {"label": "France (FR)", "value": "FR"},
    {"label": "Gabon (GA)", "value": "GA"},
    {"label": "Gambia (GM)", "value": "GM"},
    {"label": "Georgia (GE)", "value": "GE"},
    {"label": "Germany (DE)", "value": "DE"},
    {"label": "Ghana (GH)", "value": "GH"},
    {"label": "Greece (GR)", "value": "GR"},
    {"label": "Grenada (GD)", "value": "GD"},
    {"label": "Guatemala (GT)", "value": "GT"},
    {"label": "Guinea (GN)", "value": "GN"},
    {"label": "Guinea-Bissau (GW)", "value": "GW"},
    {"label": "Guyana (GY)", "value": "GY"},
    {"label": "Haiti (HT)", "value": "HT"},
    {"label": "Honduras (HN)", "value": "HN"},
    {"label": "Hungary (HU)", "value": "HU"},
    {"label": "Iceland (IS)", "value": "IS"},
    {"label": "India (IN)", "value": "IN"},
    {"label": "Indonesia (ID)", "value": "ID"},
    {"label": "Iran (IR)", "value": "IR"},
    {"label": "Iraq (IQ)", "value": "IQ"},
    {"label": "Ireland (IE)", "value": "IE"},
    {"label": "Israel (IL)", "value": "IL"},
    {"label": "Italy (IT)", "value": "IT"},
    {"label": "Jamaica (JM)", "value": "JM"},
    {"label": "Japan (JP)", "value": "JP"},
    {"label": "Jordan (JO)", "value": "JO"},
    {"label": "Kazakhstan (KZ)", "value": "KZ"},
    {"label": "Kenya (KE)", "value": "KE"},
    {"label": "Kuwait (KW)", "value": "KW"},
    {"label": "Kyrgyzstan (KG)", "value": "KG"},
    {"label": "Laos (LA)", "value": "LA"},
    {"label": "Latvia (LV)", "value": "LV"},
    {"label": "Lebanon (LB)", "value": "LB"},
    {"label": "Lesotho (LS)", "value": "LS"},
    {"label": "Liberia (LR)", "value": "LR"},
    {"label": "Libya (LY)", "value": "LY"},
    {"label": "Liechtenstein (LI)", "value": "LI"},
    {"label": "Lithuania (LT)", "value": "LT"},
    {"label": "Luxembourg (LU)", "value": "LU"},
    {"label": "Madagascar (MG)", "value": "MG"},
    {"label": "Malawi (MW)", "value": "MW"},
    {"label": "Malaysia (MY)", "value": "MY"},
    {"label": "Maldives (MV)", "value": "MV"},
    {"label": "Mali (ML)", "value": "ML"},
    {"label": "Malta (MT)", "value": "MT"},
    {"label": "Mauritania (MR)", "value": "MR"},
    {"label": "Mauritius (MU)", "value": "MU"},
    {"label": "Mexico (MX)", "value": "MX"},
    {"label": "Moldova (MD)", "value": "MD"},
    {"label": "Monaco (MC)", "value": "MC"},
    {"label": "Mongolia (MN)", "value": "MN"},
    {"label": "Montenegro (ME)", "value": "ME"},
    {"label": "Morocco (MA)", "value": "MA"},
    {"label": "Mozambique (MZ)", "value": "MZ"},
    {"label": "Myanmar (MM)", "value": "MM"},
    {"label": "Namibia (NA)", "value": "NA"},
    {"label": "Nepal (NP)", "value": "NP"},
    {"label": "Netherlands (NL)", "value": "NL"},
    {"label": "New Zealand (NZ)", "value": "NZ"},
    {"label": "Nicaragua (NI)", "value": "NI"},
    {"label": "Niger (NE)", "value": "NE"},
    {"label": "Nigeria (NG)", "value": "NG"},
    {"label": "North Macedonia (MK)", "value": "MK"},
    {"label": "Norway (NO)", "value": "NO"},
    {"label": "Oman (OM)", "value": "OM"},
    {"label": "Pakistan (PK)", "value": "PK"},
    {"label": "Panama (PA)", "value": "PA"},
    {"label": "Papua New Guinea (PG)", "value": "PG"},
    {"label": "Paraguay (PY)", "value": "PY"},
    {"label": "Peru (PE)", "value": "PE"},
    {"label": "Philippines (PH)", "value": "PH"},
    {"label": "Poland (PL)", "value": "PL"},
    {"label": "Portugal (PT)", "value": "PT"},
    {"label": "Qatar (QA)", "value": "QA"},
    {"label": "Romania (RO)", "value": "RO"},
    {"label": "Russia (RU)", "value": "RU"},
    {"label": "Rwanda (RW)", "value": "RW"},
    {"label": "Saint Kitts and Nevis (KN)", "value": "KN"},
    {"label": "Saint Lucia (LC)", "value": "LC"},
    {"label": "Saint Vincent and the Grenadines (VC)", "value": "VC"},
    {"label": "San Marino (SM)", "value": "SM"},
    {"label": "Saudi Arabia (SA)", "value": "SA"},
    {"label": "Senegal (SN)", "value": "SN"},
    {"label": "Serbia (RS)", "value": "RS"},
    {"label": "Seychelles (SC)", "value": "SC"},
    {"label": "Sierra Leone (SL)", "value": "SL"},
    {"label": "Singapore (SG)", "value": "SG"},
    {"label": "Slovakia (SK)", "value": "SK"},
    {"label": "Slovenia (SI)", "value": "SI"},
    {"label": "Somalia (SO)", "value": "SO"},
    {"label": "South Africa (ZA)", "value": "ZA"},
    {"label": "South Korea (KR)", "value": "KR"},
    {"label": "Spain (ES)", "value": "ES"},
    {"label": "Sri Lanka (LK)", "value": "LK"},
    {"label": "Sudan (SD)", "value": "SD"},
    {"label": "Suriname (SR)", "value": "SR"},
    {"label": "Sweden (SE)", "value": "SE"},
    {"label": "Switzerland (CH)", "value": "CH"},
    {"label": "Syria (SY)", "value": "SY"},
    {"label": "Taiwan (TW)", "value": "TW"},
    {"label": "Tajikistan (TJ)", "value": "TJ"},
    {"label": "Tanzania (TZ)", "value": "TZ"},
    {"label": "Thailand (TH)", "value": "TH"},
    {"label": "Togo (TG)", "value": "TG"},
    {"label": "Trinidad and Tobago (TT)", "value": "TT"},
    {"label": "Tunisia (TN)", "value": "TN"},
    {"label": "Turkey (TR)", "value": "TR"},
    {"label": "Turkmenistan (TM)", "value": "TM"},
    {"label": "Uganda (UG)", "value": "UG"},
    {"label": "Ukraine (UA)", "value": "UA"},
    {"label": "United Arab Emirates (AE)", "value": "AE"},
    {"label": "United Kingdom (GB)", "value": "GB"},
    {"label": "United States (US)", "value": "US"},
    {"label": "Uruguay (UY)", "value": "UY"},
    {"label": "Uzbekistan (UZ)", "value": "UZ"},
    {"label": "Venezuela (VE)", "value": "VE"},
    {"label": "Vietnam (VN)", "value": "VN"},
    {"label": "Yemen (YE)", "value": "YE"},
    {"label": "Zambia (ZM)", "value": "ZM"},
    {"label": "Zimbabwe (ZW)", "value": "ZW"},
]